# -*- coding: utf-8 -*-
"""Classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F-P3wHqG0s2A0cthMA8LSBKnpmBV16C7
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
import tensorflow.keras.datasets.fashion_mnist as data
import matplotlib.pyplot as plt

(x_train, y_train), (x_test, y_test) = data.load_data()

model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.Dense(100,activation='relu'),
    keras.layers.Dense(50,activation='selu'),
    keras.layers.Dense(10,activation='softmax'),
])

model.compile(loss='sparse_categorical_cross_entropy',optimizer='sgd',metrics=['accuracy'])

#model.fit(x_train , y_train , epochs=20 , validation_split=0.1)

history = model.fit(x_train , y_train , epochs=20 , validation_split=0.1)

history.history

model.evaluate(x_test , y_test)

ax , fig = plt.subplots(figsize(12,5))
ax.plt(history.history['loss'] , lable = 'loss')
ax.plt(history.history['accuracy'],lable='acc')
ax.plt(history.history['validation_loss'],lable='val_loss')
ax.plt(history.history['validation_accuracy'],lable='val_acc')