# -*- coding: utf-8 -*-
"""CNN in Keras

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11cpSRtgHVHzURRs6RS0DCrmVOABgqkF0
"""

import tensorflow as tf
from tensorflow import keras
from keras.datasets import fashion_mnist as data
import matplotlib.pyplot as plt
import numpy as np

(x_train , y_train),(x_test , y_test) = data.load_data()

x_train , x_test = x_train/255.0 , x_test /255.0

plt.imshow(x_train[0])

model = keras.models.Sequential([
    keras.layers.Conv2D(50 , 5 , padding='SAME',input_shape=[28,28,1], activation='relu'),
    keras.layers.MaxPool2D(2),
    keras.layers.Conv2D(100 , 3 , padding='SAME', activation='relu'),
    keras.layers.MaxPool2D(2),
    keras.layers.Conv2D(200 , 3 , padding='SAME', activation='relu'),
    keras.layers.MaxPool2D(2),
    keras.layers.Flatten(),
    keras.layers.Dense(100,activation='relu'),
    keras.layers.Dropout(0.4),
    keras.layers.Dense(50,activation='relu'),
    keras.layers.Dropout(0.4),
    keras.layers.Dense(10,activation='softmax'),

])

model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x_train,y_train , epochs=20 , validation_split=0.15)

